# Generated by Django 4.2 on 2023-05-05 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_variation_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='variation',
            managers=[
            ],
        ),
    ]
