# Generated by Django 4.2.5 on 2024-03-11 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_productgallery_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_variations_available',
            field=models.BooleanField(default=True),
        ),
    ]
